    #Create .env file
    - name: "Creating an empty file"
      file:
        path: "/home/orzaguri/node-weight-tracker/.env"
        state: touch

    - name: Insert configuration to the env file
      blockinfile:
        path: /home/orzaguri/node-weight-tracker/.env
        block: |
          # Host configuration
            PORT=8080
            HOST=0.0.0.0
            NODE_ENV=development
            HOST_URL= {{HOST_URL}}
            COOKIE_ENCRYPT_PWD={{COOKIE_ENCRYPT_PWD}}

          # Okta configuration
            OKTA_ORG_URL={{OKTA_ORG_URL}}
            OKTA_CLIENT_ID={{OKTA_CLIENT_ID}}
            OKTA_CLIENT_SECRET={{{OKTA_CLIENT_SECRET}}

          # Postgres configuration
            PGHOST={{PGHOST}}
            PGUSERNAME={{PGUSERNAME}}
            PGDATABASE={{PGDATABASE}}
            PGPASSWORD={{PGPASSWORD}}
            PGPORT=5432